### ISSUE TITLE
Crashes on load in SDV 1.3.28, SMAPI 2.7

### ISSUE THREAD

**Issue by plasticpal** [skuldomg/priceDrops#1]
Log is [here](https://log.smapi.io/Z4eVxbv2).

**Comment by skuldomg** [comment]
I couldn't reproduce your error but pushed an update that should catch nullpointer exceptions like the one you had. Feel free to try whether or not you still get it.

**Comment by plasticpal** [comment]
It's not crashing any more. Thanks!

**Comment by skuldomg** [comment]
Perfect :) Thanks for using my mod!
